# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recipescraper < Formula
  desc ""
  homepage "https://github.com/ohchloeho/recipescraper"
  version "0.1.2"

  on_macos do
    url "https://github.com/ohchloeho/recipescraper/releases/download/v0.1.2/recipescraper_0.1.2_darwin_all.tar.gz"
    sha256 "4f9389a312f9efe426f5be073ca9da8c8976071c2586df01bd5385c40c476e8c"

    def install
      bin.install "recipescraper"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohchloeho/recipescraper/releases/download/v0.1.2/recipescraper_0.1.2_linux_amd64.tar.gz"
        sha256 "24d251bf234be5e41fe2d179edc1a975ca1e05c4c05534877f573e637be0675f"

        def install
          bin.install "recipescraper"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohchloeho/recipescraper/releases/download/v0.1.2/recipescraper_0.1.2_linux_arm64.tar.gz"
        sha256 "fbfedd1db6d3f37267788918a7d89aef5875580b9233e158caaf2f26b02caf30"

        def install
          bin.install "recipescraper"
        end
      end
    end
  end
end
