# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recipescraper < Formula
  desc ""
  homepage "https://github.com/ohchloeho/recipescraper"
  version "0.1.1"

  on_macos do
    url "https://github.com/ohchloeho/recipescraper/releases/download/v0.1.1/recipescraper_0.1.1_darwin_all.tar.gz"
    sha256 "49b7fa2c3abc26facbed55326343ffc47582f3cbf8f8a90d49df8223a9e272b5"

    def install
      bin.install "recipescraper"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohchloeho/recipescraper/releases/download/v0.1.1/recipescraper_0.1.1_linux_amd64.tar.gz"
        sha256 "d5ebeb8cbba7ec38a6df8c530823968240e9b1f72e6e75dab954c1779a26d246"

        def install
          bin.install "recipescraper"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohchloeho/recipescraper/releases/download/v0.1.1/recipescraper_0.1.1_linux_arm64.tar.gz"
        sha256 "f1b1f06e5f07561b55266bb5cbd9106a3ae6218c82df096f47cfe978cb8864bf"

        def install
          bin.install "recipescraper"
        end
      end
    end
  end
end
